model:
  yolo_world:
    model_id: "yolo_world/l"

  sam:
    name: "xl1"
#    weight_url: "weights/xl1.pt"

  ram:
    name: "ram_plus"
#    pretrained: "weights/ram_plus_swin_large_14m.pth"
    vit: "swin_l"
    image_size: 384
    llm_tag_des: True

transform:
  image_size: 384

inference:
  class_threshold: 0.5
  confidence_threshold: 0.3
  nms_threshold: 0.5

gradio:
  server_name: "127.0.0.1"
  share: true
