model:
  yolo_world:
    model_id: "yolo_world/l"

  sam:
    name: "xl1"
    weight_url: "weights/xl1.pt"

  ram:
    image_size: 384
    pretrained: "weights/ram_plus_swin_large_14m.pth"
    vit: "swin_l"
    llm_tag_des: "datasets/openimages_rare_200/openimages_rare_200_llm_tag_descriptions.json"
    class_threshold: 0.5

transform:
  image_size: 384

inference:
  confidence_threshold: 0.3
  nms_threshold: 0.5

gradio:
  server_name: "127.0.0.1"
  share: true
